name: Jupyter Notebook Model

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
  # - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
  #   - name: Converting Jupyter notebook
  #     run: |
  #       jupyter nbconvert --to python MLPipeline.ipynb
    
  #   - name: Executing Jupyter notebook
  #     run: |
  #       python MLPipeline.py  

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Building Docker Image
      run: |
        docker build . --file Dockerfile --tag vishnunagineni/salespredictioncicd
    - name: Pushing docker image
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/salespredictioncicd

