name: Jupyter Notebook Model

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Converting Jupyter notebook
      run: |
        jupyter nbconvert --to python MLPipeline.ipynb
    
    - name: Executing Jupyter notebook
      run: |
        python MLPipeline.py
    